;              

CREATE MEMORY TABLE PUBLIC.ARTICULO(
    IDENTIFICADOR BIGINT AUTO_INCREMENT NOT NULL,
    DESCRIPCION VARCHAR NOT NULL,
    NOMBREIMAGEN VARCHAR,
    PRECIO DOUBLE NOT NULL,
    PRIMARY KEY (IDENTIFICADOR)
);

CREATE MEMORY TABLE PUBLIC.EMPRESAENVIO(
    IDENTIFICADOR BIGINT AUTO_INCREMENT NOT NULL,
    DESCRIPCION VARCHAR NOT NULL,
    TARIFA DOUBLE NOT NULL,
    PRIMARY KEY (IDENTIFICADOR)
);

           
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TEST;     

INSERT INTO PUBLIC.ARTICULO(DESCRIPCION,NOMBREIMAGEN,PRECIO) VALUES('Bote con 3 Pelotas de Tenis', 'tenis.gif',12.95); 
INSERT INTO PUBLIC.ARTICULO(DESCRIPCION,NOMBREIMAGEN,PRECIO) VALUES('Bat de Baseball de madera deBeer W1610LL','bat.gif',36.50); 
INSERT INTO PUBLIC.ARTICULO(DESCRIPCION,NOMBREIMAGEN,PRECIO) VALUES('Porterías y balón de FootBall rápido', 'porterias.gif',35.00); 
INSERT INTO PUBLIC.ARTICULO(DESCRIPCION,NOMBREIMAGEN,PRECIO) VALUES('Velero de madera de balsa','velero.gif',  15.40);

INSERT INTO PUBLIC.EMPRESAENVIO(DESCRIPCION,TARIFA) VALUES ('DHL Envio en 48 Hrs.',0.04);		
INSERT INTO PUBLIC.EMPRESAENVIO(DESCRIPCION,TARIFA) VALUES ('UPS Envio en 24 Hrs.',0.06);		
INSERT INTO PUBLIC.EMPRESAENVIO(DESCRIPCION,TARIFA) VALUES ('MEX POST Envio en 12 Hrs.',0.08);